config/routes.rb
Rails.application.routes.draw do

  get 'search/index'

  get 'protected_controller/require_user'

  post 'auth/login' => 'auth#login', as: :login
  get 'auth/logout' => 'auth#logout', as: :logout

  get 'home/index' => 'home#index', as: :home
  get 'signup'     => 'home#signup', as: :signup
  post 'home/signup' => 'home#save_user', as: :new_user
  root 'home#index'

  get 'search/(:keyword)' => 'search#index', as: :search

  resources :ratings
  resources :date_ranges
  resources :users
  resources :food_items
  resources :eateries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @user = User.new
  end

  def signup
    @user = User.new
  end

  def save_user
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to eateries_path, notice: 'Successfully signed up!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_digest)
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<main class="row align-middle" style="height:75%">
  <div class="column card">

    <h1>Welcome to <strong>ND-Menu</strong>!</h1>

    <%= form_for @user, url: login_path do |f| %>
      <div class="row">
        <div class="medium-5 columns">
          <%= f.label :email %>
          <%= f.email_field :email %>
        </div>
        <div class="medium-5 columns">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>
        <div class="medium-2 columns">
          <label>&nbsp;</label><!--fix spacing-->
          <%= f.submit 'Login', :class=>'primary button' %>
        </div>
      </div>
    <% end %>

    <p><%= link_to 'Need an account?', signup_path %></p>

    <% if flash[:message] %>
      <div class="<%= flash[:class] %> callout">
        <%= flash[:message] %>
      </div>
    <% end %>

  </div>
</main>

app/views/home/signup.html.erb
<div class="row align-middle" style="height:75%">
  <div class="column card">
    <h3>Signup</h3>
    <%= form_for @user, url: new_user_path do |f| %>
      <div class="row">
        <div class="medium-5 columns">
          <%= f.label :email %>
          <%= f.email_field :email %>
        </div>
        <div class="medium-5 columns">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>
        <div class="medium-2 columns">
          <label>&nbsp;</label>
          <%= f.submit 'Signup', class: 'success button' %>
        </div>
      </div>
    <% end %>
  </div>
</div>