config/routes.rb
Rails.application.routes.draw do

  get 'search/index'

  get 'protected_controller/require_user'

  post 'auth/login' => 'auth#login', as: :login
  get 'auth/logout' => 'auth#logout', as: :logout

  get 'home/index' => 'home#index', as: :home
  get 'signup'     => 'home#signup', as: :signup
  post 'home/signup' => 'home#save_user', as: :new_user
  root 'home#index'

  get 'search/(:keyword)' => 'search#index', as: :search

  resources :ratings
  resources :date_ranges
  resources :users
  resources :food_items
  resources :eateries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :eatery

	validates :stars, :eatery, presence: true
	validates :stars, inclusion: { in: 0..5, message: "must be in range 0-5" }
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:description, :stars, :eatery_id)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(rating) do |f| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :eatery_id %> <br>
    <%= f.collection_select :eatery_id, Eatery.all, :id, :name, prompt: true %>
  <div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :stars %>
    <%= f.number_field :stars %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>


<div class="row">
  <div class="column card">

    <%= render 'form', rating: @rating %>

    <%= link_to 'Show', @rating %> |
    <%= link_to 'Back', ratings_path %>

  </div>
</div>

app/views/ratings/index.html.erb
<div class="row">
  <div class="column card">

    <p id="notice"><%= notice %></p>

    <h1>Ratings</h1>

    <table>
      <thead>
        <tr>
          <th>Eatery</th>
          <th>Review</th>
          <th>Stars</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @ratings.each do |rating| %>
          <tr>
            <td><%= rating.eatery.name %></td>
            <td><%= rating.description %></td>
            <td><%= rating.stars %></td>
            <td><%= link_to 'Show', rating %></td>
            <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
            <td><%= link_to 'Delete', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Rating', new_rating_path %>

  </div>
</div>

app/views/ratings/new.html.erb
<div class="row">
  <div class="column card">

  <h1>New Rating</h1>

    <%= render 'form', rating: @rating %>

    <%= link_to 'Back', ratings_path %>

  </div>
</div>

app/views/ratings/show.html.erb
<div class="row">
  <div class="column card">

    <p id="notice"><%= notice %></p>

    <p>
      <strong>Description:</strong>
      <%= @rating.description %>
    </p>

    <p>
      <strong>Stars:</strong>
      <%= @rating.stars %>
    </p>

    <%= link_to 'Edit', edit_rating_path(@rating) %> |
    <%= link_to 'Back', ratings_path %>

  </div>
</div>