config/routes.rb
Rails.application.routes.draw do

  get 'search/index'

  get 'protected_controller/require_user'

  post 'auth/login' => 'auth#login', as: :login
  get 'auth/logout' => 'auth#logout', as: :logout

  get 'home/index' => 'home#index', as: :home
  get 'signup'     => 'home#signup', as: :signup
  post 'home/signup' => 'home#save_user', as: :new_user
  root 'home#index'

  get 'search/(:keyword)' => 'search#index', as: :search

  resources :ratings
  resources :date_ranges
  resources :users
  resources :food_items
  resources :eateries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/date_range.rb
class DateRange < ApplicationRecord
	belongs_to :eatery
end

app/models/eatery.rb
class Eatery < ApplicationRecord
	has_many :food_items
	has_many :date_ranges
	has_many :ratings

	validates :name, :location, :description, presence: true
	validates :name, uniqueness: true

	def inventory
		size = 0
		size = self.food_items.count
		return size
	end

	def average
		total = 0
		self.ratings.each do |r|
			total = total + r.stars
		end
    if self.ratings.count == 0
      return 0
    end
		total/self.ratings.count
	end

end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  # jarp: should be lower case and with underscores. They are defining methods
  belongs_to :eatery

  validates :name, :eatery, presence: true

  def full_price
  	String line = '$'
  	adjusted_price = '%.2f' % price
  	line = line + adjusted_price.to_s
  	return line
  end

  def to_s
    name
  end

end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :eatery

	validates :stars, :eatery, presence: true
	validates :stars, inclusion: { in: 0..5, message: "must be in range 0-5" }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :password, presence: true

  def name
  	self.email[/[^@]+/]
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

  def login
    @user = User.find_by_email params[:user][:email]
    if @user and @user.authenticate params[:user][:password]
      session[:user_id] = @user.id
      redirect_to eateries_path
    else
      flash[:message] = 'Login error'
      flash[:class] = 'alert'
      redirect_to home_path
    end
  end

  def logout
    flash[:message] = 'Logged out'
    flash[:class] = 'primary'
    session[:user_id] = nil
    redirect_to home_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @user = User.new
  end

  def signup
    @user = User.new
  end

  def save_user
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to eateries_path, notice: 'Successfully signed up!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_digest)
    end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:description, :stars, :eatery_id)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @keyword = params[:keyword]
  end
end

app/controllers/users_controller.rb
class UsersController < ProtectedControllerController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_bg
    images = []
    (1..6).each {|i| images << "bg0#{i}.jpg"}
    images.sample
  end
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/date_ranges_helper.rb
module DateRangesHelper
end

app/helpers/eateries_helper.rb
module EateriesHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="row column footer-bottom">
  <span class="float-right"><small>
    <i>Created by Will Badart, Jamie Maher, and Erin Turley</i>
  </small></span>
  <% if session[:user_id] %>
    <small>
      logged in as <%= User.find_by_id(session[:user_id]).name %>
    </small>
  <% end %></p>
</footer>

app/views/layouts/_header.html.erb
<nav class="top-bar">

  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">
        <%= link_to home_path, class: 'no-decoration' do %>
          <span class="float-right"><i class="fa fa-cutlery"></i></span>
          ND Menu&nbsp;&nbsp;
        <% end %>
      </li>
      <li><%= link_to 'Eateries', eateries_path %></li>
      <li><%= link_to 'Food Stuffs', food_items_path %></li>
      <% if session[:user_id] %>
        <li><%= link_to 'Ratings', ratings_path %></li>
      <% end %>
      <% if session[:user_id] %>
        <li><%= link_to "Logout", logout_path %></li>
      <% end %>
    </ul>
  </div>

  <div class="top-bar-right">
    <ul class="menu">
      <li>
        <%# <%= form_for @search do |f| %1> %>
        <%#   <%= f.text_field :keyword %1> %>
        <%# <% end %1> %>
        <input type="search" placeholder="Search (WIP)"></li>
      <li>
        <%= link_to search_path(keyword: @keyword) do %>
          <button class="secondary button">
            <i class="fa fa-search"></i>
          </button>
        <% end %>
      </li>
    </ul>
  </div>

</nav>

app/views/layouts/_rating.html.erb
<% @eatery.average.times do %>
    <i class="fa fa-star"></i>
<% end %>
<% (5-@eatery.average).times do %>
    <i class="fa fa-star-o"></i>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ND Menu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      body{
        background: url("/assets/<%= random_bg %>") no-repeat center center fixed;
      }
    </style>
  </head>

  <body>

    <%=render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

  </body>
</html>